// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFcWL76d7JW382z4z3Yhkze_A_eJcFy1s',
    appId: '1:1096519176708:web:4bfee54d831954e8c01b51',
    messagingSenderId: '1096519176708',
    projectId: 'online-laundry-service',
    authDomain: 'online-laundry-service.firebaseapp.com',
    storageBucket: 'online-laundry-service.firebasestorage.app',
    measurementId: 'G-PHT89FCNHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQSQCffaXrj3td0t2vxFROQu54yKHFSbM',
    appId: '1:1096519176708:android:d5076f20ca9c5460c01b51',
    messagingSenderId: '1096519176708',
    projectId: 'online-laundry-service',
    storageBucket: 'online-laundry-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXSGZA3mXGRRSqdayTWVPjxN8wRigyH8E',
    appId: '1:1096519176708:ios:4cd631c0d655263ac01b51',
    messagingSenderId: '1096519176708',
    projectId: 'online-laundry-service',
    storageBucket: 'online-laundry-service.firebasestorage.app',
    iosBundleId: 'com.quantumgrid.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXSGZA3mXGRRSqdayTWVPjxN8wRigyH8E',
    appId: '1:1096519176708:ios:4cd631c0d655263ac01b51',
    messagingSenderId: '1096519176708',
    projectId: 'online-laundry-service',
    storageBucket: 'online-laundry-service.firebasestorage.app',
    iosBundleId: 'com.quantumgrid.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFcWL76d7JW382z4z3Yhkze_A_eJcFy1s',
    appId: '1:1096519176708:web:20267cadc5f2ef3dc01b51',
    messagingSenderId: '1096519176708',
    projectId: 'online-laundry-service',
    authDomain: 'online-laundry-service.firebaseapp.com',
    storageBucket: 'online-laundry-service.firebasestorage.app',
    measurementId: 'G-7G41Q13TZ4',
  );
}
